### ISSUE TITLE
Week 1-2

### ISSUE THREAD

**Issue by lc512k** [lc512k/jl-node-app#1]
@j-mes Here are some bullet points for these first two weeks. Please do at your own pace. We'll add more as needed. Please drop me any questions in the comments of this issue if you have any.

- [x] Get familiar with the node app
- [x] Try out the GET and POST endpoints
- [x] Write some of your own endpoints
- [x] Send back some HTML to the browser (with or without handlebars)
- [x] Submit a PR with the above code 👆and add me as a reviewer
- [x] Once reviewed merge to master
- [x] Publish to heroku

**Comment by j-mes** [comment]
@lc512k I like the 👋! I wrote two endpoints, and will look into the HTML part today. Can I create views or is that for later?

**Comment by lc512k** [comment]
> Can I create views or is that for later?

Go for it!

**Comment by j-mes** [comment]
I've submitted a PR for the first few points, I'll do another one with the form soon.

**Comment by lc512k** [comment]
Looks great @j-mes! Once you've merged to master have a go at publishing to Heroku. You can have your heroku app publish automatically with every merge to `master` in this repo. Give me a shout if any issues!

**Comment by j-mes** [comment]
I have pushed this to Heroku... https://sheltered-sea-68364.herokuapp.com/ via the Heroku CLI locally.

However, I'm not sure how I can make it publish every time a merge is done in the master branch. I have integrated my GitHub account into the Heroku account in the backend, and could not find this repository.

**Comment by j-mes** [comment]
I'm looking into getting mongodb installed locally - and this seems like it can be done via homebrew. Onboard train wifi is definitely not a good idea to run that 😂

https://gist.github.com/nrollr/9f523ae17ecdbb50311980503409aeb3 - This is what I'm basing it on.
